package com.ymatou.demo1.infrastructure.db.mapper;

import com.ymatou.demo1.infrastructure.db.po.UserInfoPo;
import com.ymatou.demo1.infrastructure.db.po.UserInfoPoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserInfoPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Wed Dec 23 11:48:53 CST 2020
     */
    int countByExample(UserInfoPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Wed Dec 23 11:48:53 CST 2020
     */
    int deleteByExample(UserInfoPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Wed Dec 23 11:48:53 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Wed Dec 23 11:48:53 CST 2020
     */
    int insert(UserInfoPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Wed Dec 23 11:48:53 CST 2020
     */
    int insertSelective(UserInfoPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Wed Dec 23 11:48:53 CST 2020
     */
    List<UserInfoPo> selectByExample(UserInfoPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Wed Dec 23 11:48:53 CST 2020
     */
    UserInfoPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Wed Dec 23 11:48:53 CST 2020
     */
    int updateByExampleSelective(@Param("record") UserInfoPo record, @Param("example") UserInfoPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Wed Dec 23 11:48:53 CST 2020
     */
    int updateByExample(@Param("record") UserInfoPo record, @Param("example") UserInfoPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Wed Dec 23 11:48:53 CST 2020
     */
    int updateByPrimaryKeySelective(UserInfoPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Wed Dec 23 11:48:53 CST 2020
     */
    int updateByPrimaryKey(UserInfoPo record);
}